services:
  my-node-app:
    container_name: node-postgres-container
    image: node-postgres-image:latest
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app


